# Generated by Django 6.0.2 on 2026-02-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Отображать этот рецепт в блоке "Главный рецепт"', verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
    ]
