# Generated by Django 6.0.2 on 2026-03-07 06:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inspiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 7, 6, 49, 52, 618571, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Можно вставить iframe код напрямую', verbose_name='Код для встраивания'),
        ),
        migrations.AddField(
            model_name='video',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Отмечать, если это основное видео для рецепта', verbose_name='Главное видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vk', 'VK Видео'), ('rutube', 'RuTube'), ('other', 'Другое')], default='vk', max_length=20, verbose_name='Тип видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать название рецепта', max_length=200, verbose_name='Название видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(help_text='Вставьте ссылку на видео или iframe код', max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['title'], name='core_blogpo_title_876e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='core_blogpo_slug_36a1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['created_at'], name='core_blogpo_created_f1ebf3_idx'),
        ),
        migrations.AddIndex(
            model_name='inspiration',
            index=models.Index(fields=['title'], name='core_inspir_title_fc8b23_idx'),
        ),
        migrations.AddIndex(
            model_name='inspiration',
            index=models.Index(fields=['slug'], name='core_inspir_slug_ed143b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='core_recipe_title_c3b1df_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='core_recipe_slug_3d29ca_idx'),
        ),
    ]
