# Generated by Django 6.0.2 on 2026-03-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_video_options_video_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text='Например: 15:30', max_length=20, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на видео или iframe код', max_length=500, verbose_name='Ссылка на видео'),
        ),
    ]
