# Generated by Django 6.0.2 on 2026-03-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_video_options_video_duration_video_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Отображать в блоке "Главный рецепт"', verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True, verbose_name='Код для встраивания'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главное видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published', 'is_featured'], name='core_recipe_is_publ_49d0c3_idx'),
        ),
    ]
